KabaLabs/Cypress-Recorder

package-lock.json
package.json
src/background/background.ts
src/background/index.ts
src/code-generator/CodeGenerator.ts
src/manifest.json
tsconfig.json

Added a clean script to package.json so we can update the manifest.json in the dist folder served by parcel. Renamed index.ts to background.ts for specificity. Parcel now serving all files to chrome extension, and popup window is displaying dummy tsx components.

added manifest.json to dist folder, parcel now serving all files

---

package-lock.json
package.json
src/assets/styles/styles.sass
src/assets/styles/styles.scss
src/background/background.ts
src/constants/events.ts
src/constants/messages.ts
src/constants/ui-actions.ts
src/content-scripts/eventRecorder.ts
src/helpers/DataStore.ts
src/helpers/codeGenerator.ts
src/manifest.json
src/popup/components/ActiveRecordingBox.tsx
src/popup/components/App.tsx
src/popup/components/ClipboardButton.tsx
src/popup/components/CodeBlock.tsx
src/popup/components/CodeDisplay.tsx
src/popup/components/Footer.tsx
src/popup/components/Header.tsx
src/popup/components/InfoButton.tsx
src/popup/components/LandingBox.tsx
src/popup/components/ResetButton.tsx
src/types/types.ts

See commit messages for more details.

Clipboard, styling, code generation pipeline.

---

src/background/background.ts
src/helpers/codeGenerator.ts
src/popup/components/CodeBlock.tsx

Codegen base functionality. Event recording persists across webpages.

Codegen plus Navigation

---

src/helpers/codeGenerator.ts

fixed errant semicolons; muted enter key.

code generator bugfix

---

src/background/background.ts
src/content-scripts/eventRecorder.ts
src/helpers/codeGenerator.ts
src/popup/components/App.tsx

fixed duplicate events. fixed React state not updating after turning extension off and on, or loading extension for the first time.

Removed duplicates and fixed React state.

---

package-lock.json
src/assets/styles/styles.scss

Set position of header and footer to be fixed when scrolling code.

Set position of header and footer to fixed

---

README.md
src/background/background.ts
src/content-scripts/eventRecorder.ts
src/manifest.json
src/popup/components/App.tsx
src/types/index.d.ts

key commands work, refactored async / promises

Commands (Brad)

---

src/background/background.ts
src/manifest.json

Changed default command shortcuts. Added linux command shortcuts. Fixed bug in handleQuickKeys.

Added Non Mac Shortcuts

---

src/manifest.json

Update version number and minor changes to manifest

Update version number and minor changes to manifest

---

src/background/background.ts
src/helpers/codeGenerator.ts
src/helpers/model.ts
src/types/index.d.ts

--created Model helper class to improve modularity and readability
--improved control flow in background
--refactored CodeGen to a single export

Control flow: refactored backend for MVC

---

src/popup/components/ToggleButton.tsx

minor bug fix with disabled resume button styling to properly show it "grayed out"

minor bug fix with disabled resume button styling to properly show it "grayed out"

---

package-lock.json
src/__tests__/front-end-tests/infoButton.test.tsx
src/__tests__/front-end-tests/toggleButton.test.tsx
src/popup/components/App.tsx
src/popup/components/InfoButton.tsx

Added basic tests for info button to check for text display and that function runs on click.
minor code format updates for consistency in App.tsx and togglebutton.tsx

Added tests for info button and minor code format updates for consistency

---

package-lock.json
package.json
src/popup/components/CodeDisplay.tsx

Added basic syntax highlighting to improve UX.

Syntax highlighting

---

package-lock.json
src/__tests__/front-end-tests/__snapshots__/header.test.tsx.snap
src/__tests__/front-end-tests/__snapshots__/infoButton.test.tsx.snap
src/__tests__/front-end-tests/__snapshots__/landingBox.test.tsx.snap
src/__tests__/front-end-tests/header.test.tsx
src/__tests__/front-end-tests/infoButton.test.tsx
src/__tests__/front-end-tests/landingBox.test.tsx

Updated infoButton tests to include snapshots, cleaned up comments.
Created simple tests for landingbox just to check display text based on isValidTab state.

Updated infoButton tests to include snapshots, created simple tests for landingbox, created tests for header

---

README.md

- added feature list
- added usage instructions
- general clean up
- still needs screenshots

Upate README.md

---

package.json
src/background/background.ts
src/constants/index.ts
src/manifest.json
src/popup/components/App.tsx

implemented functional update form of setState in useEffect to improve performance. Added Push control type to improve consistency and readability.

Minor update to improve performance and consistency

---

src/__tests__/__snapshots__/toggleButton.test.tsx.snap
src/assets/styles/styles.scss
src/popup/components/ClipboardButton.tsx
src/popup/components/ResetButton.tsx
src/popup/components/ToggleButton.tsx

reset button now adhering to left side, doesn't jump on copy

Fixed reset button styling

---

src/__tests__/ToggleButton.test.tsx
src/__tests__/__snapshots__/ToggleButton.test.tsx.snap

re-implented snapshots on togglebutton.

added snapshots back to togglebutton

---

README.md

Made small but important changes to readme.md to have correct new github account and also to add Japanese blurb.

minor updates to the readme

---

package-lock.json
package.json
src/background/background.ts
src/manifest.json
tsconfig.json

-- fixed control flow bug--was getting frozen state if error in control function
-- removed onInstalled listener
--removed incremental flag in tsconfig.json

Important Bugfix to 1.0.2

---

package-lock.json
package.json
src/background/background.ts
src/constants/index.ts
src/helpers/codeGenerator.ts
src/helpers/model.ts
src/manifest.json

Fixed dbclick

---

src/background/background.ts
src/helpers/codeGenerator.ts

Add cy.url when location changed

---

package-lock.json
package.json
src/helpers/codeGenerator.ts
src/popup/components/CodeBlock.tsx

Highlighting Update Related to Issue #151
